name: cortijo_app

description: A new Flutter project.

publish_to: none

version: 1.0.9+26

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  auto_route: ^5.0.4
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  dotted_border: ^2.1.0
  dropdown_button2: ^2.0.0
  equatable: ^2.0.5
  firebase_core: ^3.8.1 #2.17.0
  firebase_messaging: ^15.1.6 #14.2.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_local_notifications: ^17.2.1
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_slidable: ^2.0.0
  flutter_svg: ^1.1.6
  fluttertoast: ^8.2.1
  get_it: ^7.2.0
  http: ^0.13.4
  image_picker: ^1.0.2
  intl: ^0.19.0
  logger: ^1.1.0
  map_launcher: ^2.4.0
  path_provider: ^2.1.0
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  signature: ^5.3.0
  slide_to_confirm: ^1.1.0
  stacked: ^3.0.1
  table_calendar: ^3.0.8
  timeago: ^3.3.0
  url_launcher: ^6.1.7
  video_player: ^2.4.8
  webview_flutter: ^4.2.2

dev_dependencies:
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.2
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/imgs/
    - assets/icons/
    - assets/mp4/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-BlackItalic.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-BoldItalic.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
        - asset: assets/fonts/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-LightItalic.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-MediumItalic.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins-ThinItalic.ttf
    #         style: italic
    - family: Quiza Pro
      fonts:
        - asset: assets/fonts/Quiza Pro Regular.ttf

#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts from package dependencies,
# see https://flutter.dev/custom-fonts/#from-packages
